### ISSUE TITLE
Allow filtering for service_ids or team_ids in table pagerduty_incident

### ISSUE THREAD

**Issue by janritter** [turbot/steampipe-plugin-pagerduty#18]
**Is your feature request related to a problem? Please describe.**
When querying longer time ranges (e.g. last 14 days) in a PagerDuty account with a lot of services and high amount of total incidents, the query takes a lot of time (last 30 days = 25 minutes).

**Describe the solution you'd like**
The PagerDuty API allows additional filter parameters like service ids or team ids which could limit the requested amount of data and therefore the query runtime significantly. I would like to implement the additional filter parameters so they are used when the user adds a where clause for team id and / or service id to the query

**Additional context**
I would be happy to also implement the options to filter by service id or team id, but not sure how this could be achieved with the current table structure, since service and team infos are json objects in the results without a dedicated team_id or service_id column.

**Comment by e-gineer** [comment]
Adding column level qualifiers for common fields so they can be targeted in requests makes a big difference to performance and a lot of sense in this case.

Question - Does the PagerDuty API support filtering on those fields?

**Comment by janritter** [comment]
Yes, both are available in the api and the used SDK. https://developer.pagerduty.com/api-reference/9d0b4b12e36f9-list-incidents

**Comment by janritter** [comment]
In case of the team id,  one incident could belong to multiple teams. Is there also a good way to reflect this in the new columns?  And have I understood it correctly that the option would be add additional columns?

If there are examples from other tables available this would help

**Comment by misraved** [comment]
Closing this issue in favour of https://github.com/turbot/steampipe-plugin-pagerduty/pull/19
